### PR TITLE
Project grading rubric

### PR DESCRIPTION
**Pull request by jon-bell**

### CODE REVIEW

**Comment by abhutta0** [comment]
-We should discuss this. 
-I will have live demos in class. I will also ask them to submit optional video demo and copy of their presentation. I would like presentation to include a number of additional items, like weekly contribution for each members, number of hours they spent (and then for overall project), along with their contact info and recent image. May be change this to 10% demo and say, each instructor may have different schedule/formats for final demos.
-For me evaluation of demos will be different too. My scores will be calculated from evaluations from me, TAs and other groups. I ask each group to score other demos.
-For 10% meetings: may be we should mention "Each instructor may require groups to submit weekly report".
-We havn't assigned points for individual reflection. May be this would be a Canvas Assignment?
-Total seems to be 90%, not 100%

**Comment by jon-bell** [comment]
Sure, please feel free to push some edits with more generic text as needed.

**Comment by mwand** [comment]
(I'm away, and don't have time to make edits, sorry.  Maybe Adeel can do these when he makes his edits.).  

The section on Final Report should say "20% Final Report".

The notes of our last meeting say

> 10% Presentation (3.5% of overall course)
> 20% Report (7% of overall course)
> Deliverables for the report will be posted later.
> We may have finer rubrics for Presentation & Report [these may also vary across sections]

So I think the details that are there have gotten ahead of what we agreed upon.  These sections should probably sat "Deliverables will be posted later."

In particular, I am unhappy that there is no requirement that the report describe the architecture of the delivered code.

I look forward to Adeel's version (perhaps in a separate branch? :)

**Comment by jon-bell** [comment]
We had a design section last year, it was not in our discussion notes so I cut it. I am OK with doing this all in just this one branch for simplicity :) 

```
### 10% Documentation - DESIGN
#### Satisfactory:
* `DESIGN.md` file contains a description of any substantive changes to the existing Covey.Town codebase, and the architecture of your new code.
* It uses CRC cards, or state diagrams or any of the other techniques that help describe the structure.
* The document is at most 4 pages (fewer pages are absolutely acceptable, consider this a rough limit) **Added 4/8**
```

**Pull request merged**
