### PR TITLE
Draft of project overview, add link to team formation

### PR DESCRIPTION
**Pull request by jon-bell**

### CODE REVIEW

**Comment by abhutta0** [comment]
4-5 member teams

**Comment by abhutta0** [comment]
Suggest updating this: "The very first deliverable for the project will be a team formation survey: you will be able to indicate
your preferences for teammates. The instructors will assign students to the teams based on a number of factors including your responses to the survey."

**Comment by abhutta0** [comment]
You may want to remove the link for the survey since each section will have its own link

**Comment by jon-bell** [comment]
I thought that from our conversation today others shared that they would like to use a single team formation form - this was what I proposed and was in the agenda. Should I update my form to NOT have the dropdown to select with section the students are in, and make it clear that it is only for my section?

**Comment by abhutta0** [comment]
In project plan, we can add this somewhere: "Your team will self-organize, as agile teams do and will use the work breakdown and schedule as the basis for weekly check-ins with your team's TA. "

**Comment by abhutta0** [comment]
Somewhere in "project implementation or plan, we should mention peer evaluations and evaluation of each sprint"

Rest looks good.

**Comment by jon-bell** [comment]
I've shared the form with you on Google Drive. Please, feel free to edit it directly

**Comment by abhutta0** [comment]
Updated!

**Pull request merged**
