### PR TITLE
Week2

### PR DESCRIPTION
**Pull request by mwand**
Added content to week2.md

### CODE REVIEW

**Comment by mwand** [comment]
I just pushed another commit 94bc7c5 to this branch, but I don't see it on this pull request.  Not sure how to proceed.

**Comment by jon-bell** [comment]
I don't see 94bc7c5 - can you paste the full SHA and/or link to where you can see it on GitHub?

**Comment by mwand** [comment]
https://github.com/neu-se/CS4530-Spring-2022/commit/3b0f0d9a748fb7d675f955e9eac80b886fbb1d66

Here's what I got when I pushed.

***@***.*** MINGW64 ~/Dropbox/Work/cs4350-5500/CS 4530 Spring
2022/WebSite (week2)
$ git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 459 bytes | 459.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:neu-se/CS4530-Spring-2022.git
   94ba7c5..3b0f0d9  week2 -> week2

**Comment by jon-bell** [comment]
There was a typo in your original message - the copy/pasted log shows 94ba7c5..3b0f0d9 . Both of those commits are here - you can see them listed on this page, they are sorted between the comments. 

It is also deployed - https://61e86170b1c47200071da0b6--objective-mclean-ad778c.netlify.app/modules/week2-knowledge-sharing-design-doc 

However, if you had open a deploy preview from an earlier commit and refreshed it, you would still see the old contents - each deploy preview gets its own unique URL. If you visit the link that the bot put in the PR ( https://deploy-preview-4--objective-mclean-ad778c.netlify.app/ ) it will take you to the latest commit.

**Comment by mwand** [comment]
I understand almost none of your message :(

I know I gave you the wrong 6 character code, sorry.  I can never remember
whether the push message is oldrev..newrev or newrev..oldrev.

**Comment by abhutta0** [comment]
Lesson 2.1: Looks ok. Slide 11 and 13 could use some pictures

**Comment by jon-bell** [comment]
These lessons look fantastic, thank you! I see only two small issues:
1. Lesson 2.1 slide 13: Is it too gross to drop one of the UML diagrams of one of the design patterns there, just so that there is a bit more to look at?
2. Lesson 2.4 slide 2: Is it intentional that the scale of UML diagrams is an empty slide? :)

**Comment by mwand** [comment]
Added pictures as per Jon's suggestion.  Also adopted some of PPT's "Design Ideas" for a few slides; see if you like the way they look.  (Some of these could become visual cues we use throughout the course)

**Review by mwand — COMMENTED** [review]
Aww, @abhutta0, you didn't like the design suggestions from PPT?  No problem.   Thanks for fixing fonts and sizes.  

I will push this branch at 5pm.

**Comment by abhutta0** [comment]
Sure. Thanks

**Pull request merged**
